### ISSUE TITLE
 UI-Student Inquiry

### ISSUE THREAD

**Issue by anjumanjum** [serviceproviderpk/SMSystem#1]
Kindly make this screen with full  functionality .Create ,Edit Delete and View (Grid )
You can follow for this  already Designed  main Section **Student  > Manage Student** .

please give ur estimated time .

Thanks

**Comment by anjumanjum** [comment]
![studentinquery](https://cloud.githubusercontent.com/assets/20067356/19409863/ac323fca-9292-11e6-9821-94ee89734ab4.PNG)

**Comment by anjumanjum** [comment]
![gridinquiry](https://cloud.githubusercontent.com/assets/20067356/19409890/25afd97a-9293-11e6-887f-de0c3d19979e.PNG)

**Comment by serviceproviderpk** [comment]
please let me know. when it's ready for testing. 

thanks

**Comment by serviceproviderpk** [comment]
Add new menu  as "Add New Student" as submenu and in grid list page, show icon of Plus (+)

**Comment by serviceproviderpk** [comment]
1) Inquiry(Father & Address)
2)ADD button in student inquiry

**Comment by mubashir633** [comment]
1) Inquiry(Father & Address)(**Fixed**)
2) ADD button in student inquiry(**Fixed**)
