### ISSUE TITLE
10/7/17 Feedback

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SMSystem#102]
1- Dashboard, Monthly Report Proper Formating and Data **(Fixed)**
2- Manage Student Search by Without DateRange **(Fixed)**
3- On Edit Student Carrier Select Auto From Model **(Fixed Nasir)**
4- Struck Off Student Sorting In Desending Order **Fixed Adil**
5- Hide Struck Off List From Manage Student Tab **(Fixed Adil)**
6- Student Profile Absent And Present of Current Month Count On Main Screen **(Fixed Adil)**
7- Result Card Name Change to Manage Annual Result. And Report Finel **(Fixed Adil)**
8- Session Time Problem **(Already 60 Minute)**
9- Previous Institute Direct From Student Table. **(Fixed Adil)**
10- Morning School Direct From Student Table. **(Fixed Adil)**
11- Attandance Summary Strength != Present+Absent+Leave **(Fixed Adil)**
12- Fee Account Show Just Assingned Acount in Readonly Form **(Fixed Adil)**
13- Add Button On Registration Time To Add Fee Account Against Staff **(Fixed Adil)**
14- Advance Fee Report **(Fixed Adil//Proc Remaining)**
15- Other Dues Name Change to Add Other Dues, And Also Student Wise **(Fixed Adil)**
16- Fee Packages to Define Fee Packages **(Fixed Adil)**
17- Sort Defaulter Students By Section **(Fixed Adil)**
18- Attandance Summary Sort by Section **(Fixed Adil)**

20- Reports **(Fixed Adil)**
=> Create SMS Event
=> Send General SMS
=> SMS Log
=> Class Configuration
=> Section Configuration
=> Subject Config. (Section Wise)
=> Add Test Round
=> Add Test Type
Other same to same
21- Mobile No. in Branch Registration and show on every report with Phone No. **(Fixed Adil)**
23- SMS Event Date Range Remove **(Fixed Adil)**

**Comment by adilshehbaz** [comment]
Estimated Time One Week

**Comment by NasirNiazkiyani** [comment]
3- On Edit Student Carrier Select Auto From Model
4- Struck Off Student Sorting In Desending Order

**Comment by adilshehbaz** [comment]
1: Class Test Report myn aik class select ki magar all classes ka data mix ho raha hay

**Comment by adilshehbaz** [comment]
Feedback Today: Send SMS to Present Student on Attandance

**Comment by tariqmtoor** [comment]
On Edit Student Carrier Select Auto From Model (Fixed Nasir). Not Fixed
