### ISSUE TITLE
SGS Feedback December 2017

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SMSystem#109]
8.C. Fee Collection krtay huay all receivables separately show hon & in ki reports b alag alg hon. Aik total collection wali reports b ho. "

13- "Date format on all screens & SMS Templates must be dd/mm/yyyy"

18-Aik excel sheet ka template add krna hay ta k uss sheet per data type kr k usay import kia ja sakay. (For new Branch).

21-Staff Biometric attendance.
22-Group Rights for Branch & staff myn sy other branches ki information hide kr dyn.

24-Hide “Other Accounts” if staff want to add staff. Only branch admin can view

27-ssl certificate

**Comment by adilshehbaz** [comment]
28- Search on Test Crud and Sorting Button **Fixed**

**Comment by adilshehbaz** [comment]
2- “Manage Stu” Menu sy “Students History” remove kr dyn. **Fixed**

**Comment by adilshehbaz** [comment]
7- Fee Menu myn Add Other Dues screen per myn nay aik student k dues add kiay magar uss section k saray students k account myn dues add ho gay. Check this error. **Fixed**

**Comment by adilshehbaz** [comment]
8-Fee Collection screen per “Save & Print” button per click krnay sy Print Preview show na ho blk receipt direct print ho jay. Aur fee collection wali screen he samnay rhay ta k next stu sy fee wasool ki ja sakay. **Fixed**

**Comment by adilshehbaz** [comment]
11-"11. Test Reports ??????????

 11.A. Test Record Management k table myn mojod lists edit nai ho rahi.
**Fixed**

**Comment by adilshehbaz** [comment]
4.A. Students profile myn jo 4 reports show ho rahi hyn un pr print ka button b laga dyn." **Fixed**

**Comment by adilshehbaz** [comment]
5-“Students Reports” myn Attendance Summary wali screen data show nai kr rahi. Is ka path ye hy. (http://starsschool.campusmanager.biz/Reports/StudnetAttendanceSummary?FromDate=12/06/2017&ToDate=12/06/2017) **Fixed**

**Comment by adilshehbaz** [comment]
6- Previous Institute wise Report & Morning School wali report myn School ka name show nai hota.
**Fixed**

**Comment by adilshehbaz** [comment]
11. B. Picture of Student Required on Single Student Test Report " **Fixed**

**Comment by NasirNiazkiyani** [comment]
14-All reports pr Sr # zaror lagayn. Fixed
15-15. All Reports k neechay Total zaror show kryn. Fixed

**Comment by adilshehbaz** [comment]
26- If we change contract status to close, inactive branch Fixed

**Comment by adilshehbaz** [comment]
16-Session time issue. Agar screen per scroll b ho rha ho to session expire nai hona chahiay.

**Comment by adilshehbaz** [comment]
17-Export to excel button sab tables per lagana hy. Fixed

**Comment by adilshehbaz** [comment]
3- "“Manage Stu” menu per “Struck off, Passed out, Terminated” etc screen per DATA sirf 1 month ka show ho. Search krnay per all data say student ko search kray.

 3.A. in screens pe data “Latest to Oldest” type sort b hona chahiay. Fixed

**Comment by adilshehbaz** [comment]
3.B. Struck off, Terminate etc ki date b table myn show krni hay. Fixed

**Comment by adilshehbaz** [comment]
9- Fee Menu myn Send SMS to defaulters wali screen theek kam nai krti. Msg Log myn shw hotay hyn mgr deliver nai hotay. **Fixed**

**Comment by adilshehbaz** [comment]
20-In SMS LOG Date Range is not functioning in “General msg” **Fixed**

**Comment by adilshehbaz** [comment]
10-Fee Reports myn Fee Collection Report aksar theek load nai hoti. Agar login hotay he load kr lyn to ok laken thora kaam krnay k baad load kryn tu error show ho jata hay.
**Fixed**

**Comment by adilshehbaz** [comment]
4-"“Student Profile” wali screen sy Students Table Remove kr dyn. Fee Collection screen wali Search bar laga dyn. **Fixed**

**Comment by nawabanjum** [comment]
19-Creat SMS Event  wali screen per Drop Down lagana hy ta k data base fields (Name, Father’s Name, Amount etc) apni marzi sy template myn add kr skyn. Sudents Serial number ki field b add krni hy
.**(done)**

**Comment by adilshehbaz** [comment]
8. B. Is it possible k Fee Collection screen per agar kisi student ko select kia jay tu us ki fee history b collection screen ki side per show ho? **Fixed**

**Comment by adilshehbaz** [comment]
23-In Super Admin, Report of Transation & Balance amount of clients is required/ **Fixed**

**Comment by adilshehbaz** [comment]
1-“Manage Students” ki all screens per “Active Stu, Struck off, Passed out etc” per search bar change kr k “Fee Collection” screen wali search bar laga dyn. (3 words liknay per name+fathers name show) **Fixed**

**Comment by adilshehbaz** [comment]
"8-A. Fee Collection Table per search bar laga dyn. Data sirf last 100 fees ka show ho magar search krny per saray data say search ho. **Fixed**

**Comment by adilshehbaz** [comment]
25-Clients say transaction krtay waqat “Other Dues” wasool krny k liay b text box add kr dyn. **This is not best option**
