### ISSUE TITLE
UI - Ledger

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#11]
![account mentu](https://cloud.githubusercontent.com/assets/19146254/19419165/2261dcb0-93eb-11e6-8bf4-b45b0d2dc047.jpg)

![ledger](https://cloud.githubusercontent.com/assets/19146254/19419160/fdad571e-93ea-11e6-9634-96665a8dcdec.jpg)

**Comment by mubashir633** [comment]
today i have assigned tasks by nawab bhai first to set the look and fill of
Initial setup which is done and secondly to create front end of ledger
which is also done. i just created the front end ( Screens ) of ledger and
print fee voucher.
-Thanks

**Comment by mubashir633** [comment]
Did Entries in student inquiry, Manage Student, student attendance, profile
and subject
Did testing of these sections and write down the issues which occurs and
handover to nasir bhai they solved many of them and rest of them are in
progress.
-Thanks
