### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SMSystem#110]
1. Plz replace **info@campusmanager.biz** with **starshighschool@live.com** for demo request in **campusmanager.biz**. **FIXED**

2. Show BRANCH Screens to a person who requests for demo. Not ORGANIZATION screens. **FIXED**

3.  LEDGER & FEE TRANSACTION History not show exact data.

4. In CONTRACT show defaulters list & send BRANDED SMS options. **FIXED**

5. Serial # is required at Award List (Exam-> Student Award List). **FIXED**

6. Phone Number is required at Defaulters List. (Fee Management-> Fee Reports->Defaulter Students). **FIXED**

7. PRINT FEE VOUCHER required in Fee Management. (Bulk & Single Print).

8. Customers Contact Info Report is required for super admin. Column Headings must be (Branch Name, Contact Person, Cell #, Address, Balance Amount toward branch, etc). **FIXED**

9. Strucked off student ko search krnay k liay us ka session select krna parta hy. jo k nai hona chahiay.
10. PASSED OUT students myn sahi data show nai ho rha. **Fixed**
11. kis aik student ki fee history check kryn phir kisi aur student ko select kryn per puranay stu ki history he show hoti rehti hay.  **Fixed**
12. strucked off student ki fee collect krtay waqt collection fields show nai hotay.
13. kia ye check kr lia gya hay k DEMO REQUEST per bnanay wala account 48 hours k baad automatically inactive ho jay.

**Comment by adilshehbaz** [comment]
Plz replace info@campusmanager.biz with starshighschool@live.com for demo request in campusmanager.biz. **Fixed**
Show BRANCH Screens to a person who requests for demo. Not ORGANIZATION screens.**Fixed**
In CONTRACT show defaulters list & send BRANDED SMS options.**Fixed**

**Comment by adilshehbaz** [comment]
Max length on send sms to defaulter **Fixed**

**Comment by adilshehbaz** [comment]
5. Serial # is required at Award List (Exam-> Student Award List). **Fixed**

**Comment by adilshehbaz** [comment]
Phone Number is required at Defaulters List. (Fee Management-> Fee Reports->Defaulter Students). **Fixed**

**Comment by adilshehbaz** [comment]
Customers Contact Info Report is required for super admin. Column Headings must be (Branch Name, Contact Person, Cell #, Address, Balance Amount toward branch, etc) **Fixed**

**Comment by adilshehbaz** [comment]
Contract Transaction Issue **Fixed**

**Comment by adilshehbaz** [comment]
FEE TRANSACTION History not show exact data. **Fixed**

**Comment by adilshehbaz** [comment]
Slider images change on campus manager **fixed**

**Comment by adilshehbaz** [comment]
Email changes on cmapus manager **fixed**

**Comment by adilshehbaz** [comment]
award list count issue **fixed**

**Comment by adilshehbaz** [comment]
Fee Collection Discount Issue **Fixed**
