### ISSUE TITLE
Fee Reports And User Rights

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SMSystem#113]
1- Fee Collection Report show all accounts of fee 
2- User Rights levels
Organization => Branch => Staff

**Comment by nawabanjum** [comment]
@adilshehbaz  please explain more about Fee Collection Report show all accounts of fee

**Comment by adilshehbaz** [comment]
On Fee Collection we collect fee in different accounts like monthly fee, admission fee etc.

Need to show all accounts on Fee Collection Report.
