### ISSUE TITLE
Weekly Report

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#19]
1st Week

Student Iquiry
Student Registration Chart of Account
Voucher
Manage profile

2d Week

Inquiry List / CRUD
Student Attendenace
Employee Attendenace
Class configuration
Initial System Setup Configuration (in progress)

**Comment by engrumairbutt** [comment]
Looking pretty astonishing. Waiting for uploaded version

**Comment by serviceproviderpk** [comment]
Agreed. but without initial setup completion, uploading is not meaningful for us..

**Comment by serviceproviderpk** [comment]
**1st Week**

Student Iquiry
Student Registration Chart of Account
Voucher
Manage profile

**2d Week**

Inquiry List / CRUD
Student Attendenace
Employee Attendenace
Class configuration
Initial System Setup Configuration (in progress)

**3rd Week**

Initial setup configuration
 -Organization
-Branch Management
 -Fee Package Management
-Class&Section Management

**4th Week**

Student Profile
Test system
Result 
Exam type
Ledger
Trail balance

**Comment by serviceproviderpk** [comment]
**6th Week**

1. Fee Receipt
2. Voucher Entry
3. Attendance Report
4. Test Type lookup
5. Account Group
