### ISSUE TITLE
UI- Student Registration

### ISSUE THREAD

**Issue by anjumanjum** [serviceproviderpk/SMSystem#2]
Kindly Design this Screen.
And dnt forget to time estimation

![student reg](https://cloud.githubusercontent.com/assets/19146254/19418947/d6e50de6-93e7-11e6-8bd0-ea4160f556f9.jpg)

Thanks

**Comment by serviceproviderpk** [comment]
1) Image control move on top right and following discussed instructions
2) In student contact info in  record of Father and mother phone number on edit mode is not showing
mother and guardian Phone# are conflicting
3) more than one entry   with same id validation issue in student 
4) personal and father phone number is not showing in grid
5) Photo not showing in edit mode

**Comment by serviceproviderpk** [comment]
1) Image control move on top right and following discussed instructions
2) In student contact info in record of Father and mother phone number on edit mode is not showing
mother and guardian Phone# are conflicting
3) more than one entry with same id validation issue in student 
4) personal and father phone number is not showing in grid (Help)
5) Photo not showing in edit mode (In progress)
6) + (Add icon in student list page) **(Fixed)**
