### ISSUE TITLE
Student inquiry

### ISSUE THREAD

**Issue by engrumairbutt** [serviceproviderpk/SMSystem#21]
![capture8](https://cloud.githubusercontent.com/assets/22872210/20337058/7d53b45a-abf0-11e6-90f3-be16903e1e41.JPG)
here are some issues
contact number field should be justified i.e. 03**-******* or not more than 11 standard digits and cant accept alphabets
CNIC field must be justified by *****-********-*
Inquiry date must be by default today's
there must be some type of justification that we may know how many students are transferred as registered students and how many inquiries are in vain

**Comment by engrumairbutt** [comment]
![capture233](https://cloud.githubusercontent.com/assets/22872210/20337170/33a5bf3c-abf1-11e6-9ea3-30a4563a2212.JPG)
Registration must be auto generated, another serial must be here which looks like that
a drop button with named 'Group' and after that every group must be defined a new auto generated serial number+manually amended but unique number.
cnic and phone number restriction must be added
size of picture to be attached must be defined i.e. max size 30kb
Phone number title may be changed as Phone#1, Phone#2, Cell#1, Cell#2.......instead of father and mother
multi filters may be added to search any specific student

**Comment by engrumairbutt** [comment]
![capture9](https://cloud.githubusercontent.com/assets/22872210/20338099/c0bd35ee-abf6-11e6-8bc0-44314496db1a.JPG)
all section data must  be save after pressing the 'save' button instead individual saving

**Comment by mubashir633** [comment]
Contact numbers in whole project are justified now (**Fixed**)
CNIC numbers are also justified (**Fixed**)
Phone number titles are changed as Phone#1, Phone#2, Cell#1, Cell#2 (**Fixed**)
