### ISSUE TITLE
UI-Exam Type

### ISSUE THREAD

**Issue by anjumanjum** [serviceproviderpk/SMSystem#22]
Please Do this Screen .and follow the DB table **ExamType**
Give your estimation type

**Comment by mubashir633** [comment]
their is no screen is showing nawab bhai please check

**Comment by anjumanjum** [comment]
yar ye Databse ka table check kr lo .is me just aik drop down ho gi session ki aur aik textbox hoga aur branchid and orgnaziton id login user ki aay gi.
