### ISSUE TITLE
UI-User Rights

### ISSUE THREAD

**Issue by anjumanjum** [serviceproviderpk/SMSystem#25]
Dear Mubashir kindly do this Screen and make it full functionall.Screen is just like we have discussed in office.and i also done the **User Group** Crud and create the procedure for **User Rights** procedure name is  **SP_GetRights** it is added in  **UserRightService**

**Comment by anjumanjum** [comment]
@mubashir633  please tasks ko smj k kia kroo mn ne 10 mint lgay hn ap k kam pe .get latest le k check kr laa ap ne jo kia tha ur mn ne jo kia h

**Comment by serviceproviderpk** [comment]
Please add proper data in Class like
Class1
Class2
Class3
upto class10
in each class add 2 section
Section A
Section B
and also add proper fee according to the class

-Use same layout page for  report/other pages
-Add All Posible rights in "Rights" Table
 and set same RightId, in Enum

**Comment by serviceproviderpk** [comment]
USE [SchoolDB]
GO
/****** Object:  StoredProcedure [dbo].[Sp_GetAllRegistrationGroup]    Script Date: 12/27/2016 4:44:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



create Proc [dbo].[Sp_GetLoggedUserRights]

@UserGroupId int
as
begin

SELECT        User_Group_Rights.RightID, User_Group_Rights.ActionType, UserGroup.GroupName, User_Group_Rights.GroupId
FROM            User_Group_Rights LEFT OUTER JOIN
                         UserGroup ON User_Group_Rights.GroupId = UserGroup.UserGroupID
WHERE        (UserGroup.UserGroupID = @UserGroupId)


 end

**Comment by serviceproviderpk** [comment]
ok
