### ISSUE TITLE
UI - Student Attendence

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#3]
![student attendence](https://cloud.githubusercontent.com/assets/19146254/19418956/0689a1a6-93e8-11e6-856c-07a1b8b8532d.jpg)

**Comment by mubashir633** [comment]
First of all i did not find any table of my assigned work. their was no table against my assigned work so i created one dummy table name **DailyAttendance**  after that i create Services, Repositories, DTO controller, views and JS of that table almost  finished with this table i am not going to check in code today alright just to prevent from any error tomorrow i will show to all of you then i will do check in. if you want the screen shot i can provide it on demand on skype.

**Comment by serviceproviderpk** [comment]
1) Try to place all fields in one row.
2)  Load  and Mark button in second row.

**Comment by mubashir633** [comment]
1) Try to place all fields in one row. (Fixed)
2) Load and Mark button in second row. (Fixed)
