### ISSUE TITLE
Pending Points

### ISSUE THREAD

**Issue by NasirNiazkiyani** [serviceproviderpk/SMSystem#30]
ResultCardEdit
TestSystemEdit
Employeesalary(complte)
StudentProfile(plz test this module)

**Comment by NasirNiazkiyani** [comment]
nwab bhai plz Initial Setup ko be check ker lijye ga..ek dafa...

thank u

**Comment by serviceproviderpk** [comment]
C = 1, // create
        V = 8, //view 
        Cv = 9, //view 
        Vd = 10, //view edit
        Cdv = 11, //create delete view
        Ve = 12, //view edit
        Cev = 13, // create
        Dev = 14, //delete edit view
        Cdev = 15, //create delete edit view
        CdvAl = 27,  // Cdevi
