### ISSUE TITLE
Student serial number

### ISSUE THREAD

**Issue by engrumairbutt** [serviceproviderpk/SMSystem#33]
Apart form registration number another field named serial number is required which may be act like this

- first a drop down named 'Group' having the different sections in school like primary section, middle section and high section, minimum six groups are required which may be hard codded or configuration based

- after the group selection from the drop down auto generated serial number may be shown in the field w.r.t. every field i.e. every group has unique prefix of serial number, this serial number may be editable also

**Comment by NasirNiazkiyani** [comment]
Do you want to add unique serial number in "Student" that will depend on  "Selected Group" unique group, ?

**Comment by engrumairbutt** [comment]
dear @NasirNiazkiyani previously developed registration number will be used as it is. a new filed must be append to the student data 'Group' and 'Serial Number'
--groups must be shown in a drop down and every group must continue its unique serial number
--this serial number is editable also i.e. manually changeable
--when a serial number is changed newly entry of the same group must start from last entered/saved serial number
--serial number must be identical

**Comment by engrumairbutt** [comment]
dear @NasirNiazkiyani  kindly consult @serviceproviderpk  sb for more details. We have discussed it on phone.
