### ISSUE TITLE
outstanding

### ISSUE THREAD

**Issue by NasirNiazkiyani** [serviceproviderpk/SMSystem#35]
1. result card edit mode (not complete)
2. issue # 8 (UI-Fee vouchers is ka kon sa crud ha ye point github per ha)    (**FIXED**)
3. issue # 9 Fee Generate ka edit mode ni hua ha(nwab bhai us ka edit mode ho ga ya ni plz wo check  ker lijiye ga)
4. issue # 12 (test system edit mode (not complete) **(Fixed)**
5. issue # 13 (is points ke sacreen kon si ha mjhy pta ni chal rha plz is ko be check ker lijiye ga) **(Not in used)**
6. Chart of accounts Add and Edit issue...**(FIXED)**
7. class configuration Edit issue....class configuration ke edit mode mian fee packages main exception ati ha...**(FIXED)**

**Comment by serviceproviderpk** [comment]
8. Please implement user rights for all views, as i have implemented for "Student Inquiry" but of create,edit, delete, will be visible on the basis of  User Rights. if user has view only access "Submit/Save button" will be hidden as hided for Inquiry.

**Comment by serviceproviderpk** [comment]
8. @mubashir633. Thanks for User Rights Implementation, Get Latest Db and create 2 Groups
   Default Group (Give it only view Access)
   Full Access: (Create/edit/view/delete/All)
(i think default group already created)
add all rights in relevant group.then test it, control are visible and as we are expecting?

we can make this screen easy by some logic
