### ISSUE TITLE
UI - Student Profile for the portal

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#4]
![student profile for the portal](https://cloud.githubusercontent.com/assets/19146254/19418980/96a2f6b6-93e8-11e6-9a2e-982c28830c7e.jpg)

![left menu](https://cloud.githubusercontent.com/assets/19146254/19419065/02ee55f4-93e9-11e6-982d-53c48ed9357e.jpg)

**Comment by anjumanjum** [comment]
ALi Design this screen and u can follow student inquiry screen for design perspective.
and give your estimated  time

**Comment by serviceproviderpk** [comment]
1) In student men as new sub item as  "Student Profile" when user click on on it, the above screen will be dispplayed
