### ISSUE TITLE
UI - Employee Registration

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#5]
![employee registration](https://cloud.githubusercontent.com/assets/19146254/19419076/503de4fa-93e9-11e6-96f6-2daf13f003f3.jpg)

**Comment by anjumanjum** [comment]
ALi Design this screen and u can follow student inquiry screen for design perspective.
and give your estimated time

**Comment by Maaz1013** [comment]
Abc
