### ISSUE TITLE
Final Outstanding Task

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#50]
@engrumairbutt  Please write outstanding task in this issue

**Comment by serviceproviderpk** [comment]
1. Reports
   a) Please mansion name of reports

**Comment by engrumairbutt** [comment]
Top priority tasks:
•	Test system report—sample attached
•	Round report—html designed
•	Fee receipt—sample attached
•	Fee collection report—sample attached
•	Defaulter list—sample attached
Functionality to be developed:
•	SMS on all events
•	Portals for parents/students
•	First page designing
•	New organization setup
Improvements required:
•	Salary mechanism
•	Fee mechanism
•	Chart of account
•	Exam system
Minor bugs:
•	Bugs in Fee and discount mechanism
•	User rights and branch system
Reports:
1.	Student’s registration report
2.	Area wise strength report
3.	Contact information
4.	Sibling strength report
5.	Leaving certificate
6.	Character certificate
7.	Student ID card
8.	Attendance detail report
9.	Attendance summery report
Fee:
10.	Fee vouchers/Manual slip
11.	Fee receipt
12.	Defaulters List
13.	Fee collection report
Exam:
14.	Round Report
15.	Test system report-1
16.	Test system report-2
17.	Test system report-3
18.	Result card
Accounts:
19.	Voucher printing
20.	Ledger printing
21.	Trial balance/PL/BS printing
22.	Cash book/daily expense report
23.	Standard chart of account
Employee:
24.	Employee registration
25.	Salary slip
26.	Salary detail report
27.	Employee attendance summery
28.	Employee attendance report

**Comment by engrumairbutt** [comment]
Top priority reports:
Exam:
[results1.xlsx](https://github.com/serviceproviderpk/SMSystem/files/698326/results1.xlsx)
[results2.xlsx](https://github.com/serviceproviderpk/SMSystem/files/698327/results2.xlsx)
![report3 cretira](https://cloud.githubusercontent.com/assets/22872210/21841441/03d5c344-d804-11e6-88bf-50333c9e40e3.JPG)

excel file is not being attached here so i am sending these reports via mail however these reports are sent through skype also
actually these are three reports in exam urgently required
round report
student report
class wise report in a specific date range

**Comment by engrumairbutt** [comment]
dear sir,
kindly amend the following task
Fee receipt must print automatically as we save the data in fee receipt form.
Reports Layout formation i.e. all the reports and forms may have single layout so we can move to and forth any page or report easily
student inquiry student when confirmed and introduced to manage student, 'group no.' dose not map accurately
all reports may have accessibility on single page/UI
all reports are requested to have designed according to the provided layout i.e. samples are again attached
total marks added in the subjects are not showing accurately in the test system
Thanks

**Comment by engrumairbutt** [comment]
Kindly hide the emty columns from the report 1 and report2 in exam.
