### ISSUE TITLE
Final Feedback

### ISSUE THREAD

**Issue by engrumairbutt** [serviceproviderpk/SMSystem#51]
Top priority:
Kindly hide the empty columns from the report 1 and report2 in exam.

**Comment by serviceproviderpk** [comment]
1) Small bugs(discussed with nasir in details)
2) Fee discount at run-time (discount on collection screen)
3) SMS on Fee generation/collection/Defaulter/inquiry/registration)
4) Fee report changing

**Comment by serviceproviderpk** [comment]
@engrumairbutt  Please confirm which sms API we should use for sms and send format of each sms that will be send.

and signup for SMS API and send me its credentials.

**Comment by engrumairbutt** [comment]
@serviceproviderpk  boss discussed in detail with @anjumanjum , we use gsm modem for sending the sms. gsm modem will be installed at the client end and used to sen the sms. however the deatails of sms are given as under:
SMS Features:
SMS on following events with the parameters
Inquiry:
•	Student Name
•	Father Name
•	Inquiry Date
•	Branch name
•	Cell#1
•	Class
Registration:
•	Student Name
•	Father Name
•	Registration Date
•	Branch name
•	Cell#1
•	Class
•	Section
•	DOB
Attendance:
•	Student name
•	Father name
•	Attendance date
•	Attendance status
•	Class
•	Section
•	Branch name
Fee generation:
•	Class
•	Section
•	Student name
•	Father name
•	Fee generation date
•	Fee generate amount
•	Balance amount
•	Due date
Fee Collection:
•	Class
•	Section
•	Student name
•	Father name
•	Fee collection date
•	Fee collected amount
•	Balance amount
•	Branch name
Fee Defaulters:
•	Class
•	Section
•	Student name
•	Father name
•	Due date
•	Balance amount
Test system:
•	Class
•	Section
•	Student name
•	Father name
•	Subject obtained/total
•	Class position

**Comment by engrumairbutt** [comment]
Following fileds are showing the data of other branches, so filters of that fields must be modified
Student contct pop-up---class (is pop-up me class ki compulsion b khatm krni hy)
Defaulter list pop-up---class (is pop-up me class ki compulsion b khatm krni hy)
Student Attendence Screen---class (is pop-up me class ki compulsion b khatm krni hy)
Daily attendance of students---class (is pop-up me class ki compulsion b khatm krni hy)
All student attendencce ---class (is pop-up me class ki compulsion b khatm krni hy)
Student summery---class(is pop-up me class ki compulsion b khatm krni hy)
Fee Receipt Screen---class 
Student fee collection report---class (is pop-up me class ki compulsion b khatm krni hy)
Test system---class
Result card---class
Test report1---class (is pop-up me class ki compulsion b khatm krni hy)
Test report---class (is pop-up me class ki compulsion b khatm krni hy)
Section---class (is pop-up me class ki compulsion b khatm krni hy)
Grid modification:
Class definition
Data edit ni hota,
New package k lye kia kam krna hoga??---us k charges e define ni hoty hn…
