### ISSUE TITLE
Sms Feedback (20 March 2017)

### ISSUE THREAD

**Issue by NasirNiazkiyani** [serviceproviderpk/SMSystem#54]
1 ) font style modification on all reports for report headers (Nasir)(Done)
2) Fee collection report is required on just half page, and hence setting has to be finalized (Nasir)(Done)
3) Fee collection report class and section validation removal (Nasir)(Done)
4) defaulter list dosnt show any data when class and section are not selected (Nasir)(Done)
5) on fee registration screen the registration group is showing for all the branches, isy sirf us specific branch ka data show krana chahye and is ka auto increment b kam ni kr rha hy **(Nawab bhai)**
6)while converting student from inquiry to registration, registration date and registrion code are not by-default selected and registration group field kharab ho jati hy (Nasir)(Done)
7) In BussinessManager.SendSms function,
key/values which are used for sending sms please add keys, in web.config
i have added below keys
<add key="smsapi_username" value=""/>
    <add key="smsapi_password" value=""/>
    <add key="smsapi_MaskName" value=""/>
you can add more if requried
 **(Nawab)**

Thanks

**Comment by engrumairbutt** [comment]
sms events are generating every 15 mints creating much problem
sms problem for gsm modem
session screen dosnt sending the info of branch id and section id while saving the data

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Please take a look on  (3)

**Comment by engrumairbutt** [comment]
asif bhai sms ab phr ni ja rhy hn, kindly check krye gaa!!

**Comment by NasirNiazkiyani** [comment]
@engrumairbutt  ok main check kerta hn.

**Comment by NasirNiazkiyani** [comment]
session screen dosnt sending the info of branch id and section id while saving the data **(fixed)**

**Comment by engrumairbutt** [comment]
Dear Asif Bhai,
Dear Nawab bhai,
issue is not resolved still. actually i have under estimated the issue. on the new branch configuration the new data is not updated in either table as it was working previously. to tackle this i shift the system a step back where we start it, but again the same issue. on creation of new branch the system is not generating the auto configuration in following tables
class configuration
section
chart of account
Fee charges

apart from this another issue raises that pre-configured data has vanished from the database. i don't know why but it has happened last day.
Thanks

**Comment by engrumairbutt** [comment]
Asif bhai ik issue bht twater sy aa rha hy,
student registration, student inquiry and fee collection py agr 2 dafa save py click krn tu double entry ho jati hy, is ka daikh ln koi timer lgna hy hr save k press k bd ya jo b bhtr ho but wo dobule entry sy jaan chut jaye...
one thing more stuedent group ki compulsion remove krni hy student regristration screen sy

Best Wishes & Regards,

 

Ehtisham ul Haq
