### ISSUE TITLE
UI- User Rights

### ISSUE THREAD

**Issue by engrumairbutt** [serviceproviderpk/SMSystem#56]
when we create an employee, after then we change the group of that employee, that user vanishes from the employee list, hence appropriate rights cant be amended to the users

**Comment by engrumairbutt** [comment]
When a new class is generated and charges are not updated in the list of that specific class, after that class is not editable. menas k class bd me edit ni hoti

**Comment by engrumairbutt** [comment]
1. un-accurate figure of number of students on dashboard
2. graph showing false figures regarding the number of students
3. inactive classes must not shown in all the pop-ups, screens--fee must not generated for such students--fee collection screen must not shown such students
4. test reports setting formation on single page, heading of columns and re-setting of page, two test only at a time, date time formation, registration code must be hidden, obtained, total, percent field must be at the end of the report
5. session time out
6. caps lock not functioning in the database-issue
7. terminated/pass-outs/struck-off students are showing in some reports/pages
8. terminated 'confirmed' must be replaced by 'Restore'. option of character certificate/school leaving certificate in pass-outs/struck off/terminated
9. on fee collection by-default account must be cash in hand
10. voucher head account by default selection
11. save button return the page on the grid on grid
12. search students bar in the fee collection screen
13. fee collection report class section criteria if not selected, reports nothing
14. Defaulter list/fee collection report sorted on section wise
15. fee receipt detail must be hidden on the fee management menu
16. serial group auto increment selection
17. picture not adding in the database for united academy

**Comment by engrumairbutt** [comment]
@serviceproviderpk @anjumanjum

**Comment by engrumairbutt** [comment]
New branch issues still not resolved, when created new branch the auto configuration not amended

**Comment by serviceproviderpk** [comment]
@engrumairbutt  & @anjumanjum  Latest code is published on   sms.technobizz.co

Please confirm which issues are still pending.

**Comment by serviceproviderpk** [comment]
@engrumairbutt  Latest is release is uploaded on http://starsacademy.campusmanager.co/

Please test all issues/changes, if any issue please update status here.

Thanks,

**Comment by serviceproviderpk** [comment]
@engrumairbutt  Please confirm which issues are not fixed yet from above??

Nawab debug the issue of multi sms, i will upload latest release again

**Comment by serviceproviderpk** [comment]
1. on  http://localhost:17619/FeeReceipt/Index/   implement new rights, Can Edit Amount
