### ISSUE TITLE
Exam issues

### ISSUE THREAD

**Issue by engrumairbutt** [serviceproviderpk/SMSystem#57]
Class test report issues
Selected criteria
url: starsschool.campusmanager.co
user name: shs_suchyari@campusmanager.co
password: adminsuchyari
ExamExam ReportsClass Test Report
Class 8th section 8th boys
![image](https://user-images.githubusercontent.com/22872210/27028578-98d49a00-4f7e-11e7-8f8d-1c27462a7ba0.png)
 
•	**Problems 1- all report is not showing on single page. Shuru me kafi jaga khali hy, report must fit on page in landscape mode.**(done)
**•	Total test 4 show hoty hn yaha. Ye sirf 2 e show hony chahye.**(D
one)
![image](https://user-images.githubusercontent.com/22872210/27028593-a58a715c-4f7e-11e7-8057-7c71edcdc6b5.png)
 
•	# ****I just select the critera for class 8th and section 8th boys, but the report is showing the data for other section also. Other section k sirf first column me data show ho rha hy. Isy sirf jo section select kiya hy us ka data e show krana chahye**(Done)**

 
ExamExam ReportsStudent Test Report
Class 8th section 8th boys
![image](https://user-images.githubusercontent.com/22872210/27028606-b2836b48-4f7e-11e7-82cd-7b3a5a1c67cb.png)
 
**Check the searching criteria, I have select the section 8th boys but the student field is showing students for other section of same class**(Done)
![image](https://user-images.githubusercontent.com/22872210/27028615-b980fdf2-4f7e-11e7-90a7-076fdac3aa58.png)
 
**Again the report is not showing the full data on one page. It must show all subject on single page. **And test yaha b 2 e hony chahye hn. side py b jaga khali hy kafi is report me b.**(D
one)**(done)

**Comment by NasirNiazkiyani** [comment]
Fixed....

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Any change in DB or Storeprocedure for this task?
