### ISSUE TITLE
UI - Student Registeration

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#61]
Enable SMS/Email Notification  Flag in web.config for testing we will disable Notifications.

**1. Search by CNIC while student registration
**- In Student "Admission Inquiry" and " Manage Students"  in Search Dropdown there shuld be "CNIC",  to search inqiury or student by Father CNIC**(done)

**2. Print all option class and section wise**(done) 

**5. Global list of students for struck off and their searching procedure (Create a new page show list of students who are struck off)**(done) 

**5. Start date, end date -- date picker for the manage student record**((done))
**6. Searching criteria--student name, father name, class, section, registration code** (done)
**7. Promotion history, complete log must show with date and remarks 
StudentHistory(StudentHistoryId,StudentID,CreatedDate,CreatedByUserId,Details,Comments)
Track Inquiry,registration,promotion,struck off black list.**(done)
**11. Date format DD/MM/YYYY**(Done)
**9. Student pic must show in registration form, in case of unavailability, no image attach message may shown** (Done)

**13. Report admission list branch wise, show the data of all the new admission in the organization and then branch, wrt date criteria** ( (Done))
**18. Character certificate**(done)

**20. Session time out increase**(done)
**21. Fee receipt size quarter page sized**(done)
17. Struck off, pass out, defaulter students search by date range(done)
**12. For registration form, it must be on single page, only cell1  and cell2**(done)

14. Report Region wise  (get list of unique regions from students, show list of student with status
@anjumanjum  has following store precedure in db to support this task.
**spGetRegion for dropdown (store procedure not working)**
**spGetStudentRegionWise for grud(Done)**
)
**19. Report monthly current student list group by new admission, pass out, struck off. On organization level it is hyper linked and herirically branch level and then student level** (Done)
**15. Report of previous Institute wise list (Done)**

10. Grid column sequence as per provided (pending)
8. Logo transparent (pending)

**16. Mechanism for academy students to record their morning school, college 
 (As per our discussion In student Registration page add new field "MorningSchool" it will be visible when  domain/subdomain is 'Academy' to check it

in web.config and new  key . '<key ='IsAcademy' value='true or false'>

in "Student" menu add new link "Student by Morning School'**(done)

**we will filter student by morning school** (done)

**4. Super admin should show all branches data without selecting the specific branch (add new links system summary show all branches, classes  count of student)**(done)
------------------------------

**Comment by serviceproviderpk** [comment]
(10)(3) @engrumairbutt  Please explain it.

**Comment by serviceproviderpk** [comment]
19. **Exp:**  Date Ranger Picker and Drop down status  and show list of Student Branch

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  I have explained task#16

**Comment by NasirNiazkiyani** [comment]
Task #16

@if (System.Configuration.ConfigurationManager.AppSettings["IsAcademy"].ToString() == "true")
                                    {

                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="control-label" for="birthdate">Morning School</label>
                                            @Html.TextBoxFor(a => a.MorningSchool, new { @class = "form-control", placeholder = "" })

                                        </div>
                                    </div>
                                    }
sir db morning school ke field daal ker code main chck laga diya ab wo domain wala check web.config main laga dien.is acadmy true or false wala??
And sir ye be bta dien ke student registration ke page per jo hum ne mornig sachool ke field ka textbox lagaya ha us main user ke likhy ga i mean us ke value kiya ho gi??filed to wo string ke ha.

**Comment by NasirNiazkiyani** [comment]
10. Grid column sequence as per provided (pending)
8. Logo transparent (pending)

**Comment by serviceproviderpk** [comment]
3. Done by @nawabanjum 
4.  Only in  Manage Students & Inquiry ki Grid
sequence will be  Class, Name (first name and lastname) , Father Name and so on....

**Comment by serviceproviderpk** [comment]
5. In All Grids show latest record First.
