### ISSUE TITLE
UI- Fee

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#62]
1. Three folds fee challan form(Fixed)
2. Duplicate challan form management and manage its history(fixed)
4. Remove fields in fee receipt form
5. Collected fee amount should be by default selected (Fixed)
6. Collected fee for the advances should also autofill and work in such a way that it increase it by a month fee plus the ledger balance(Fixed)
7. On fee collection form all the data should autofill and its sub data is displayed in the remaining fields as part of labels (Fixed)
8. Over all generated fee should be shown(Fixed)
9. Report of total fee generated head wise and its collection in specific date range must be shown (Fixed)
10. Defaulter list two SMS template first reminder, second reminder should send separately before and after the due date(Fixed)

**Comment by serviceproviderpk** [comment]
@WaqarShah  Please create below screen

![image](https://user-images.githubusercontent.com/19146254/27804003-0879ee46-6046-11e7-8145-1d7d9ec32a68.png)

**Comment by WaqarShah** [comment]
Above report is completed you are requested to please follow the path : 
 Reports/NewFeeReceipt/

**Comment by serviceproviderpk** [comment]
1&2  in Grid there will be  Option "View Challan" and "Generate  Challan"
View only display and "Generate" will create and save in "History" Table.
