### ISSUE TITLE
DB - Change Script

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#64]
For any change in DB or Store procedure, we will track here. for future use.

**Comment by serviceproviderpk** [comment]
1) New table "PreviousInstitue" to support a report
script is available  in "TFS"

**Comment by serviceproviderpk** [comment]
2. New Table "StudentHistory"
[StudentHistory.txt](https://github.com/serviceproviderpk/SMSystem/files/1116742/StudentHistory.txt)

**Comment by NasirNiazkiyani** [comment]
[changedbscript.txt](https://github.com/serviceproviderpk/SMSystem/files/1133002/changedbscript.txt
[changedbscript.txt](https://github.com/serviceproviderpk/SMSystem/files/1133003/changedbscript.txt)

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  do new entry in Github instead of "Editting"

**Comment by NasirNiazkiyani** [comment]
4. change in procedure validateuser
[change in procedure validateuser.txt](https://github.com/serviceproviderpk/SMSystem/files/1135203/change.in.procedure.validateuser.txt)

**Comment by NasirNiazkiyani** [comment]
5. GetAllConfiguration procedure
[GetAllConfiguration.txt](https://github.com/serviceproviderpk/SMSystem/files/1139021/GetAllConfiguration.txt)

**Comment by NasirNiazkiyani** [comment]
6. GetProfileDetail Procedure
[GetProfileDetailProcedure.txt](https://github.com/serviceproviderpk/SMSystem/files/1139029/GetProfileDetailProcedure.txt)

**Comment by NasirNiazkiyani** [comment]
7. Get Morning School Dropdown
[GetMorningschooldropdownlist.txt](https://github.com/serviceproviderpk/SMSystem/files/1139786/GetMorningschooldropdownlist.txt)

**Comment by NasirNiazkiyani** [comment]
8 . Get student Morning school wise
[getstudentMorningschoolwise.txt](https://github.com/serviceproviderpk/SMSystem/files/1139788/getstudentMorningschoolwise.txt)

**Comment by NasirNiazkiyani** [comment]
[studentDateForChracterCertificate.txt](https://github.com/serviceproviderpk/SMSystem/files/1149146/studentDateForChracterCertificate.txt)

**Comment by NasirNiazkiyani** [comment]
[changedb19July2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1160512/changedb19July2017.txt)

**Comment by NasirNiazkiyani** [comment]
[26julydbchange1.txt](https://github.com/serviceproviderpk/SMSystem/files/1174320/26julydbchange1.txt)

**Comment by NasirNiazkiyani** [comment]
[26julydbchange2.txt](https://github.com/serviceproviderpk/SMSystem/files/1174322/26julydbchange2.txt)

**Comment by NasirNiazkiyani** [comment]
[ChangeDbScript2August2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1195037/ChangeDbScript2August2017.txt)

**Comment by NasirNiazkiyani** [comment]
[SpDuesDetail6Aug.txt](https://github.com/serviceproviderpk/SMSystem/files/1203361/SpDuesDetail6Aug.txt)

**Comment by NasirNiazkiyani** [comment]
[SpDuesDetail7Aug.txt](https://github.com/serviceproviderpk/SMSystem/files/1205832/SpDuesDetail7Aug.txt)

**Comment by NasirNiazkiyani** [comment]
[07082017.zip](https://github.com/serviceproviderpk/SMSystem/files/1206080/07082017.zip)

**Comment by NasirNiazkiyani** [comment]
[DbChanges9August2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1209487/DbChanges9August2017.txt)

**Comment by NasirNiazkiyani** [comment]
[DbChanges12August2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1219994/DbChanges12August2017.txt)

**Comment by NasirNiazkiyani** [comment]
[13Augst2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1220609/13Augst2017.txt)

**Comment by NasirNiazkiyani** [comment]
[15AugDbChanges.txt](https://github.com/serviceproviderpk/SMSystem/files/1229047/15AugDbChanges.txt)

**Comment by NasirNiazkiyani** [comment]
[NewProcedureForDataRefresher(23Aug).txt](https://github.com/serviceproviderpk/SMSystem/files/1246758/NewProcedureForDataRefresher.23Aug.txt)

**Comment by NasirNiazkiyani** [comment]
[DbChange27Aug2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1254378/DbChange27Aug2017.txt)

**Comment by NasirNiazkiyani** [comment]
[30AugDbChages2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1264773/30AugDbChages2017.txt)

**Comment by NasirNiazkiyani** [comment]
[DbChange31Aug2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1268151/DbChange31Aug2017.txt)

**Comment by NasirNiazkiyani** [comment]
[DbChange8Sep2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1286032/DbChange8Sep2017.txt)

**Comment by NasirNiazkiyani** [comment]
[DbChanges15Sep.txt](https://github.com/serviceproviderpk/SMSystem/files/1304568/DbChanges15Sep.txt)

**Comment by NasirNiazkiyani** [comment]
[Dbchange23Sep2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1325474/Dbchange23Sep2017.txt)

**Comment by NasirNiazkiyani** [comment]
[Dbchanage24sep2017.txt](https://github.com/serviceproviderpk/SMSystem/files/1326888/Dbchanage24sep2017.txt)

**Comment by serviceproviderpk** [comment]
[defaultsettingsupate.txt](https://github.com/serviceproviderpk/SMSystem/files/1327154/defaultsettingsupate.txt)

[SP_.txt](https://github.com/serviceproviderpk/SMSystem/files/1327157/SP_.txt)

**Comment by NasirNiazkiyani** [comment]
[dbchanges27sep2017.bak.txt](https://github.com/serviceproviderpk/SMSystem/files/1335201/dbchanges27sep2017.bak.txt)

**Comment by NasirNiazkiyani** [comment]
[dbchange28Sep2017.bak.txt](https://github.com/serviceproviderpk/SMSystem/files/1338512/dbchange28Sep2017.bak.txt)
