### ISSUE TITLE
UI - Login

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#66]
**I have created  "StoreProecure" we will use it  validate USER

Sp_ValidateUser**(done)

we will discuss it .

**Comment by NasirNiazkiyani** [comment]
ok sir main is ko abi imlement kerta hn

**Comment by WaqarShah** [comment]
Comments from Asif:
@NasirNiazkiyani  when user is logged in on top right side
there should be following link
Edit Profile
Change Password

**Comment by NasirNiazkiyani** [comment]
ok sir.
sir is ke store procedure bnaney hain ya apne bna diye hain???????

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  
var branchDetails = _profile.GetProfileRecord(brnachid).FirstOrDefault();

above is not best practive, you are getting list then you are getting one from list.
Store Procedure should return single record instead of List. Please modify it. thanks.

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Did get chance to fix it.

**@NasirNiazkiyani
var branchDetails = _profile.GetProfileRecord(brnachid).FirstOrDefault();

above is not best practive, you are getting list then you are getting one from list.
Store Procedure should return single record instead of List. Please modify it. thanks.

where single record is required get single form Database instead of getting list.**(done)

**Comment by NasirNiazkiyani** [comment]
Fixed.....

**Comment by serviceproviderpk** [comment]
@adilshehbaz 
use some box like

![image](https://user-images.githubusercontent.com/19146254/28398572-38737634-6d21-11e7-8ef3-718a014d6519.png)


if its manageable in short time.

**Comment by serviceproviderpk** [comment]
2. Please add "Remember me" check box.

**Comment by serviceproviderpk** [comment]
3. When User is logged in  "on top right side bar" there should be two more link
"Edit Profile" and  "Change Password"

**Comment by serviceproviderpk** [comment]
4. Also remove inbox link
![image](https://user-images.githubusercontent.com/19146254/28398837-8ee67a56-6d22-11e7-80e0-052c81683c84.png)
