### ISSUE TITLE
UI - LookUP

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#67]
**In look repository

Create an few function   FindStudent  that will bind students drop down, this storeprocedure will return following fields

ID,Name

Name will be combination of the following fields.
 (first name last name  + fathers+class+section.registration number)

if registeration is is from other table then leave it.**(Done)

sir is ka procedure  bana  diya ar services be bna diya ha ar sir Student ,StudentInquiry , and Report ke controler main bind kerwa di ha. Dropdown ke Function main Bind kerwia ha

**Comment by NasirNiazkiyani** [comment]
Fixed..

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani Please remove

**Comment by NasirNiazkiyani** [comment]
@serviceproviderpk  sir kiya romove kerna ha?jo combination bnaya tha dropdown ke liye wo remove kerna ha ar pheley ke tra he simple student ke dropdown list show kerwanih ha??
