### ISSUE TITLE
SMS Feedback 18/7/2017

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SMSystem#71]
1-On Star School login Show Star School Logo **Adil (Fixed)**                 
2-SuchYari Branch not available dashboard of  SuperAdmin Dropdownlist of all branches **Adil (Fixed)**
3-At Superadmin Dashboard show all deta of all branches e.g: show all active students of all branches, while admin select branch then show only branch deta otherwise show all deta **(Nawab) (Fixed)**
4-Show Logo on branch dashboard their is an error while uploading logo **(ASIF)Fixed**
5-Resolve the issue of decimal at addStudent e.g:1.0000 to 1.00 **(ADIL+ASIF)Fixed**
6-Resolve the issue of photo uploading at addStudent, **(ADIL)Fixed**
7-Change Morning School to Morning Institute at addStudent **Adil (Fixed)**
8-Use Loading gif while popup opens **(Adil)Fixed**
9-Hide StudentReports/Branch Wise Students from all branches, only super admin can access **(Asif)**
10-Attendence change to Attendance Spalling mistake **Adil (Fixed)**
11-Show Previous Institute on addStudent Page, remove from navbar **(Nawab)(Fixed)**
12-In student report Change System Summary to Activity log **Adil (Fixed)**
13-In student report/ region wise students,,, show dropdownlist of regions which comes from student tables/ regions.......use a filter which show every region at once,,, e.g: if we register two students both having same region....in drop down list show region at once don't repeat **(Nasir)**(Fixed)
14-In student report/ monthly student report popup dropdownlist change confirmed to Admited inquiries and Rejected to immature inquiries **(Adil)Fixed**
15-Show Student Name as ADIL not as adil on every list, certificate, fee challan **(ADIL)Fixed**
16-Hide Fee Collection data from staff **(ASIF)**
17-In Fee Generate/ single challan form / while user search for student name fill all the fields, Section, Class. **(Nawab) (Fixed)**
18-Change Print Vocture to Print Recipt  **(ADIL)Fixed**
19-Decrease Fee Recipt Size to 1/3rd of page **(Adil)Fixed**
20-Show also name of staff member which is collecting fee and also generate a report of fee collected by this person. **(Nasir)**(Fixed)
21-In addStaff change Father CNIC to CNIC **Adil (Fixed)**
22-In staffRegistration show a drop down list of staffType(managementStaff, otherStaff) **(**(Nasir)**)** **(Fixed)**
23-In AdvanceFee show balance not paidAmmount **(not an issue)** at  balance field, their is an error and also show student class auto, **(Nawab) Fixed**
24-in General SMS, show a dropdown list for class and section to send sms.. When user select class and don't select any section send sms to all class when user select section send sms to section of that class, when user don't select any class or section send sms to all, **(Nawab) (Fixed)**
25-in Fee Report/ Fee Colelction Report,, show fee collection of all school while user don't select any class or section **(Nasir)**(Fixed)
26- on send Sms to defaulter hide filed of message and show reminder sms field only,, while user select default from event category send default msg, else while he select reminder send reminder **(Nawab)** **Fixed**
27-In Daily Attandance don't send sms on save button,, First User attandance class and save it then verify and then click on send sms to present and send sms to absent **(Nawab)** (fixed)
28-show a option of restore in ManageStudent/Passout section  **(Nasir)**(Fixed)
29-show total class, total absent and total present on attandance **(Nawab)****(Fixed)**
30-Show search funtionally on all sections of manage student, passout, terminated, struckoff **(Nasir)Fixed**
31-On student certificate show Phone, Date only, Name in Capital , Monthly Fee, Fee Paid at Admission Time,  **(Nasir)Fixed**
32- show student name only in capital in leaving certificate **(Adil)Fixed**
33-Change Student Certificate to Student Certificate List in left side navbar **Adil (Fixed)**
34- Hide "Add button" for owner  **(Asif)Skip**
35-Concurrency handling while amending the specific student data **(Asif)Fixed**
36-Report monthly current student list group by new admission, pass out, struck off. On organization level it is hyper linked and herirically branch level and then student level **(Nawab)(Fixed)**

**Comment by adilshehbaz** [comment]
1-Fixed

**Comment by NasirNiazkiyani** [comment]
13-Fixed
22-Fixed
28-Fixed
25-Fixed

**Comment by serviceproviderpk** [comment]
@adilshehbaz  What about this issue

4- Show Logo on branch dashboard their is an error while uploading logo 
**(What about this issue, are you able to fix it by giving write access to the folder)**?
8- Use Loading gif while popup opens
(Please use BlockUI before start and end of each function like

App.blockUI("body");
App.unblockUI("body");

**Comment by adilshehbaz** [comment]
1-Show Logo on branch dashboard their is an error while uploading logo (ASIF)
2-Resolve the issue of decimal at addStudent e.g:1.0000 to 1.00 (ADIL)
3-Use Loading gif while popup opens (ASIF)
4-Hide StudentReports/Branch Wise Students from all branches, only super admin can access (Asif)
5-Show Previous Institute on addStudent Page, remove from navbar (Asif)
6-Hide Fee Collection data from staff (ASIF)
7-show total class, total absent and total present on attandance (Nawab)
8-Show search funtionally on all sections of manage student, passout, terminated, struckoff (Nasir)
9- Hide "Add button" for owner (Asif)
10-Concurrency handling while amending the specific student data (Asif)
11-Report monthly current student list group by new admission, pass out, struck off. On organization level it is hyper linked and herirically branch level and then student level (Nawab)
