### ISSUE TITLE
Feedback  24 July 2017

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#72]
1- On Admission Inquiry show also date and time for search. (admission inquiry men agr date and time sy search krna ho tu) **(Nasir)**Fixed
2- On Attandance save all attandance class by class and then they print and verify all attandance and then send sms to all by clicking one button (pehly class wise attandance lagti jaye save hoti jaye phr wo print nikal k verify kr ain aur a k aj ki attandance dekhen wahan ek button ho send sms to all tu sab ko sms chala jaye) **(Nawab)Fixed**
3- show a check box on manage student if they want to passout/terminate/struckoff multiple students (single student passout b ho raha terminate b struck off b,, agr multiple student krne hon tu koi option nahi hai sath men agr chk box a raha ho har student k tu us ko select kr k wo passout b kr len aur terminate b)**(Nawab)**
4- On sms log show list as branch wise and also they search by date there is list of all student showing in sms log...(Jab user login hota hai admin sy tu us ko sb student ka sms log show ho raha hai wahan py na koi branch ki option hai k kis branch ka hai r na hi date ki search hai k date wise dekh saken)**(Nasir)**Fixed
5- verify GSM sms method (GSM method sy sms ja rahy hain ya nahi)  **Done before but now Need GSM** 
6- In test system show only that test which is taken, on print form there is a list of all four test if one test is taken others three are blanks so kindly show only that test which is taken other wise not **(Asif)**
7- On selecting branch their is no change in name and logo of branch on layout,,, and in report  **Fixed by asif**
8- On successful popup UnblockUI not working... when we add deta or edit and save it a successful popup accure but UnblockUI not working there **(Nawab) Fixed**
9- Kindly give an option in exam/testreport/result card if they want to print all students result cards,,, their is only option to print result card of single student. **(Asif)**

**Comment by serviceproviderpk** [comment]
7- on choosing "Name and logo" will be changed. there are two things
a) Login User and his profile Picture, its  working fine. if user has added his profile picture.
b) on Right Side, there are branches list, if any one is selected then its value is already selected.
c) I am unable to Check in report, because  on Crud Branch " Edit Photo is not working"

**Comment by serviceproviderpk** [comment]
8- Block UI not working perfectly in all screens.

**Comment by adilshehbaz** [comment]
Block UI now working fine on every page

**Comment by adilshehbaz** [comment]
Class attandance report don't showing daily attandance report

**Comment by adilshehbaz** [comment]
Reports/ViewAllReportSinglePage/ this page not showing any report on search
