### ISSUE TITLE
Feedback Internal

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#73]

**Comment by adilshehbaz** [comment]
1-Kindly give an option in exam/testreport/result card if they want to print all students result cards,,, their is only option to print result card of single student. (Asif)
1-Attandance Save nahi ho rahi hai aur na hi report men show ho rahi hai
2-System setting men report men jo bhi select kr len kuch show nahi hota

**Comment by serviceproviderpk** [comment]
1. @adilshehbaz  I can see, Attendence date is saved in DB.
![image](https://user-images.githubusercontent.com/19146254/28600231-2d932126-71ca-11e7-821c-d1017fc51e56.png)

**Comment by serviceproviderpk** [comment]
@adilshehbaz 

1-on login page reduce verticle gap between text boxes, as i have explain already.
2- Date Format in  All Calender should me  DD/MM/YYYY . set it from BussinessManager in all sytem
 after modifying test, its workign fine in add/edit and saving and displaying date properly.
 also change the date format in  Searching Date Picker controls.

3- Searching on Manage Students not working If search by  "NIC"



3- Selected Grid font size is looking small.
- Manage Enquiry/Manage Students formatting of page, button looking like zig zag
