### ISSUE TITLE
Feedback 10 Aug2017

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#77]
Suggestions: 

2.(View All) k button ka name (Absent Student List) rakh dyn aur us myn list b sirf absent students ki show hone chahiay.**(Done Nasir)**
3.kisi class ki attendance Update krny k liay re-open kryn tu pehlay save ki hui information show nai hoti. saray absent students dobara mark krny partay hyn. **(Done by Nawab)**
4.Date ka format sub jaga per DD/MM/YYYY kr dyn.
5. General Msg ka number formate e.g k tor per display kr dyn **(Fixed)**
6. Genral message  page not working **(Fixed)**
12. Date Formatting issue in "Registeration form" **(Fixed)**
7. ISD column, class position column in the both exam reports. i.e. ISD -> check the latest row/column percentage and auto analyse. if greater percentage then add keyword 'improved', if less add keyword 'Decline' and if same percentage than 'Sustained' keyword must be added
8.Multi print of student test reports
9.Students/ parents portals to check their children record such that all student for a single parent must be shown collectively
while uploading the data on web, the waiting page must designed
**10.on attendance screen 'All view' button must be replaced by 'verify Present Students' and add a new button 'verify absent students'****(Done by Nasir)**
1.Class Attendance Mark krtay huay students search ki option honi chahiay.
11. website for the school users of a general template

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Please work on above task.
Thanks,

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Please work on task according to the sequecne

**Comment by NasirNiazkiyani** [comment]
sir main Employee Account waley task per kaam ker rha hn wo nawab bhai ne assign kiya ha..wo khy rhy thay pheley wo kerna ha task.

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Please work on  point 8&10

**Comment by NasirNiazkiyani** [comment]
ok sir...point 10 to raat ko main ne ker diya tha us thora sa kaam rhta ha ar us ke bad 8 per kaam karoun ga.
