### ISSUE TITLE
UI - Fee Vouchers

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#8]
![fee vouchers](https://cloud.githubusercontent.com/assets/19146254/19419133/0a03a244-93ea-11e6-92fa-ece57a2d460d.jpg)

**Comment by mubashir633** [comment]
today i made new screen named Print Fee voucher, i just did its screen
through DTO and functionality of save and edit is not done yet. code is
error less.
-Thanks
