### ISSUE TITLE
Task Priority

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#83]
this task is used to set the Priority of tasks.

**Comment by serviceproviderpk** [comment]
1. https://github.com/serviceproviderpk/SMSystem/issues/79 (Adil)
2. https://github.com/serviceproviderpk/SMSystem/issues/80 (Adil)
3. https://github.com/serviceproviderpk/SMSystem/issues/81 (Adil)

**Comment by adilshehbaz** [comment]
1- 80 Fixed
2- 81 Fixed

**Comment by serviceproviderpk** [comment]
1. @NasirNiazkiyani  UI - Reports #85

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Please take a look on below task and message me when you are available to discuss the these points.
![sms](https://user-images.githubusercontent.com/19146254/29737140-7399993c-8a22-11e7-9577-4f921d2b0622.jpg)

**Comment by NasirNiazkiyani** [comment]
ok sir....

**Comment by NasirNiazkiyani** [comment]
1: Sections Active/inActive (Done by Nasir)
2: Subject Active/InActive (Done By Nasir)

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani 
UI - Print #86
