### ISSUE TITLE
UI- Change Password

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#84]
1-if user is logged and try to change his password, if user click on "Cancel" it should  redirect  to Dashobard
and if user click on "Save" it should validate the input.
if user click  right now, its doing nothing.
![image](https://user-images.githubusercontent.com/19146254/29494216-b770c72e-85be-11e7-8ed0-93794bbde045.png)
2-on edit account(http://localhost:22048/Account/EditUserProfile/), email should be readonly.
3- from this page remove profile type and set it as hidden field. its huge secruity risk.

**Comment by adilshehbaz** [comment]
Fixed,,,

Required Message Not Showing when we enter nothing in change password :(
