### ISSUE TITLE
UI - Reports

### ISSUE THREAD

**Issue by serviceproviderpk** [serviceproviderpk/SMSystem#85]
Student reports main student by morning school, report hay mager uska data kahan enter krna hay?

@NasirNiazkiyani Nasir, Please check and update with steps.

**Comment by NasirNiazkiyani** [comment]
(sir is ke flow ke liye hum ne webconfig main IsAcadmy ke name se ek bit rakhi ha.jab us ke value True ho gi to Create student ke sacreen per ek textbox show ho ga MorningSchool ke name se us main us student ke school ka name enter karein gein......than report main us school ka name show ho ga.ar wahn se enter ker ke hum us school ke students search ker lein gein)
