### ISSUE TITLE
1: by me

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SMSystem#88]
1: Fee collection by person report myn date range is required. **(Done By Nasir)**
2: overall defaulter list ko classwise sort kr dyn **(Done By Nasir)**
3: student atrendance: agar current date ki attendance mark ki ja chuki hy tu msg should be shown. Isi trah agar sms send kiay ja chukay hyn tub b msg show ho ta k sms dobara na send kiay ja skyn. 
4: print fee voucher: recieving person ka name by default print hona chahiay(Done By **Nasir)**
5: stars college myn sb branches k staff ka data share ho rha hy. Means aik branch ka staff baqi myn b show ho raha hy.**(Done By Nasir)**

**Comment by tariqmtoor** [comment]
Please check it

**Comment by serviceproviderpk** [comment]
@NasirNiazkiyani  Please take a look on it.

**Comment by NasirNiazkiyani** [comment]
ok sir...
