### ISSUE TITLE
By me 2

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SMSystem#89]
1: Stars College domain myn total 2 branches hyn jin k sms templates aik dojay myn mix ho rhay hyn
2: Sections k table myn just inactive section show ho rhay hyn. All section show honay chahiay. agar table myn section k samny check box lag jay js sy pata chalay k ye active hy ya incative tu zyada behter ho jayga.**(System Sitting ke menu main 2 links hain 1)sections and 2)unActive Sections .........Sections main Active sections arhy hain and UnActive sections main unActive a rhy hain ar un Active main Active ka Options be ha Again Active kerney ke liye.)()**
3: Exams myn Number of tests ka issue abhi tak solve nai hua
4: Result k sms send nai ho rhay

**Comment by NasirNiazkiyani** [comment]
1: Stars College domain myn total 2 branches hyn jin k sms templates aik dojay myn mix ho rhay hyn
(templates to branch ke base per he show rhy hain main ne Recheck kiya ha....ap please is page ka name bta dein ya sacreen short send ker dien)


3: Exams myn Number of tests ka issue abhi tak solve nai hua **(Is Issue ko please detail main explain ker dien)**

**Comment by tariqmtoor** [comment]
T1' T2 nai blk aik month myn jitny test huay hyn wo report myn show hony chahiay. 


Eg: T1' t2' t3' t4

**Comment by serviceproviderpk** [comment]
3. @NasirNiazkiyani  I will fix this issue.

**Comment by serviceproviderpk** [comment]
1.  @tariqmtoor  as I explained login and edit template.
