### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SMSystem#90]
![untitled](https://user-images.githubusercontent.com/29690582/30047873-e7cafd66-922c-11e7-9790-111e600ac76c.png)
![untitled1](https://user-images.githubusercontent.com/29690582/30047874-e9383254-922c-11e7-97bb-0d1bf7b503c1.png)
![untitled2](https://user-images.githubusercontent.com/29690582/30047875-eb25e4a8-922c-11e7-9baa-fe89c64239f9.png)
![untitled3](https://user-images.githubusercontent.com/29690582/30047877-ed2ed8a4-922c-11e7-9ffc-d3e439f8fd27.png)

**Comment by adilshehbaz** [comment]
**RFR**

**Comment by serviceproviderpk** [comment]
Fixed.
