### ISSUE TITLE
Pending Issues till 7th September 17

### ISSUE THREAD

**Issue by tariqmtoor** [serviceproviderpk/SMSystem#92]
[Suggestions.docx](https://github.com/serviceproviderpk/SMSystem/files/1283534/Suggestions.docx)

1:	In “Inquiry” and “Manage Students” screens, this date range does not have any effect. **(Done By Nasir)** **(ye range picker bilkul thek working ker rhy hain please is ko again check ker lein fromdate and todate ke selection kerney ke bad un ke years be check ker lein.ke same hain different. )**

4: 	Student Profile myn Error: Current month September hy jbk profile myn August show ho rha hay. Jab details button pr click ikrn tu details correct show hoti hay. (Done By Nasir)

7: 	Please Remove Email Address from titles of all reports  **(Done By Nasir)**. And add cell numbers in replacement

8: 	In “Students Reports”, The report named as “Monthly Students Report” is not working properly. Please Change its name as “Monthly Reports”.**(Done By Nasir)**

9: 	In “Student”  menu, Previous Institute ka link remove kr dyn. Student add krty huay jo Institute likhyn gay wo automatically “Previous Institute Report” myn show hona chahiay. **(Done By Nasir)**

16:	Sections aur Subjects ko Active/Inactive krny k liay jo apny alag alag screens lagai hyn wo bilkiul b theek nahi hay. Active/Inactive Sections & Subjects must be shown in same screen. **(Done By Nasir)** **(Sections and Subjects ke single sacreen ker di ha ar ek new column daal diya status ke name se ar us main check box ha jo active hn gein wo checked hn gein ar unActive unchecked hn .row per click ker ke edit mode main ap use Active and Unactive ker saktey hain)**

15:	Date range SMS log pe lagani thi. Ap ny templates pe laga di jis ka koi use nai hay. SMS Log pe iss liay lagani hay ta k her month branches sy billing ki ja sakay. (General msg+SMS Evcent Log) dono per date range lagani hay **((Done By Nasir))**
 

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

2:	Date Format must be dd/mm/yyyy in all screens.
3: 	Present day ki attendance lagatay huay first screen per b “Verify” wala button laga dyn ta k check kia ja sakay k aj ki attendance mark ho chuki hay ya nai. **(Confusion)**

 10:	 Staff: this menu needs a lot more intension.  Kia ye mumkin hay k staff add krtay huay field add kr di jay k issay fee collection k rights hyn ya nahi. Agar hayn tu account b assign kr dya jay.
11: 	Staff attendance ko bio matric krna hay.  
12:	Test Record Management myn Test ko Attendance k sath link na kryn.  
13: 	Test ka record dynamic hona chahiay. T-1, T-2, T-3 Remove kr dyn. Aik date range myn aik subject k jitney test huay hyn utnay e show honay chahiayn.
 
14:	Multi Students Test Report lazmi chahiay. Yani ail click pe pori class k her students ki alag alag report.

 

17:    Data Backup Excell Format myn Download krny ki option b hone chahiay **(Fixed)**

--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

5: 	Manage Student myn student add krtay huay “Religion” & “Medium” items add kr dyn. Iss k sath “Morning School” (Commints myn : Only for Academy) b add krna hay.**(FixedByAdil)**

6: 	Students Registration Form must be formatted according to the Prospectus given to u. **(FixedByAdil)**

**Comment by tariqmtoor** [comment]
Snapshot of Errors is also attached in word file to understand the issues

**Comment by NasirNiazkiyani** [comment]
15:	Date range SMS log pe lagani thi. Ap ny templates pe laga di jis ka koi use nai hay. SMS Log pe iss liay lagani hay ta k her month branches sy billing ki ja sakay. (General msg+SMS Evcent Log) dono per date range lagani hay (Confusion) (ye Dono sacreen kaun si hain jin per date time lagana please in Dono sacreens ke Urls paste ker dien ta ke main un sacreens per picker laga sakoun )

**Comment by NasirNiazkiyani** [comment]
**Pending Tasks:**

2:	Date Format must be dd/mm/yyyy in all screens.
3: Present day ki attendance lagatay huay first screen per b “Verify” wala button laga dyn ta k check kia ja sakay k aj ki attendance mark ho chuki hay ya nai. (Confusion)

10:	Staff: this menu needs a lot more intension. Kia ye mumkin hay k staff add krtay huay field add kr di jay k issay fee collection k rights hyn ya nahi. Agar hayn tu account b assign kr dya jay.
11: Staff attendance ko bio matric krna hay.
12:	Test Record Management myn Test ko Attendance k sath link na kryn.
13: Test ka record dynamic hona chahiay. T-1, T-2, T-3 Remove kr dyn. Aik date range myn aik subject k jitney test huay hyn utnay e show honay chahiayn.

14:	Multi Students Test Report lazmi chahiay. Yani ail click pe pori class k her students ki alag alag report.
15:	Date range SMS log pe lagani thi. Ap ny templates pe laga di jis ka koi use nai hay. SMS Log pe iss liay lagani hay ta k her month branches sy billing ki ja sakay. (General msg+SMS Evcent Log) dono per date range lagani hay (Confusion)

17: Data Backup Excell Format myn Download krny ki option b hone chahiay


5: Manage Student myn student add krtay huay “Religion” & “Medium” items add kr dyn. Iss k sath “Morning School” (Commints myn : Only for Academy) b add krna hay.(Confusion)

6: Students Registration Form must be formatted according to the Prospectus given to u.

**Comment by tariqmtoor** [comment]
Ms Word ki file b attached hy. Usay view kr lyn snapshot add hyn. Ap ki confusion doour krny k liay
