### ISSUE TITLE
Pending Issues

### ISSUE THREAD

**Issue by NasirNiazkiyani** [serviceproviderpk/SMSystem#93]
15:	Date range SMS log pe lagani thi. Ap ny templates pe laga di jis ka koi use nai hay. SMS Log pe iss liay lagani hay ta k her month branches sy billing ki ja sakay. (General msg+SMS Evcent Log) dono per date range lagani hay (Confusion) (ye Dono sacreen kaun si hain jin per date time lagana please in Dono sacreens ke Urls (Path) paste ker dien ta ke main un sacreens per picker laga sakoun wesay mjhy smjh ni lag rei ap kaun si sacreen per range picker lagana chatey hain)

**Comment by tariqmtoor** [comment]
Sms log wali screens

**Comment by NasirNiazkiyani** [comment]
Url please????

**Comment by serviceproviderpk** [comment]
System Settings > Sms Log

URL

http://starsschool.campusmanager.biz/SystemSMSEventsLog/Index

**Comment by serviceproviderpk** [comment]
remove from sms template

**Comment by serviceproviderpk** [comment]
it is already added in #92
