### ISSUE TITLE
Meeting Feedback 16/9/2017

### ISSUE THREAD

**Issue by adilshehbaz** [serviceproviderpk/SMSystem#96]
1- Database Backup Daily Base at 11:55 PM **(Asif)**Fixed

2- Remove Student Registration Group From Registration Of Student and also From System Settings **(Fixed Adil)**

3- Activity Log Report Which User Add New Student and Modify Student **(Nasir)**Fixed

4- Character Certificate Title Formating **(Fixed Adil)**

5- Direct Print Command Fee Collection Screen **(Asif)**Fixed

6- Add Line Between Fee Receipt Challan Print **(Fixed Adil)**

7- Add Account1 and Account2 Field in Branch Registration Form (Add New Table of Bank Accounts) **(Adil)**Fixed

8- Add Bank Account1 or Account2 on Fee Challan Which is Given on Branch Registration  **(Adil)**Fixed

9- Chalan Form Print Single on Every Page when Generate whole Class Chalan **(Fixed Adil)**

10- Check Spell of All Project **(Asif)**Fixed

11- Add All Old Present and Other Fields on Test Report Which is Hidden in New Report **(Nawab) (FIXEdD)**

12- Test Report Print Change T(1) to T-1 **(Nawab)  (FIXEdD)**

13- Absent Student In Test Show "A" **(Nawab) **Fixed

14- Test Report For Class Every Single Student On Single Page **(Adil Fixed)**

15- If New Student Added His Test Report in This Class **(Nawab) (FIXEdD)**

16- Option to assign fee account while staff registration. **(Nawab/Nasir)**

17- New Domain for external clients, **(Suggestion By Abudl Satar)**  **(Asif)**Fixed

18- Fileupload Extension **(Showed Alert on wrong file fomat ....Fixed Adil)**

19- Date Format Same on all screens (SMS) also **(Asif)**

20- Red * on all required fields **(Fixed Adil)**

21- Quick Registeration form on student (only required field show) **(Adil)  (FIXEdD)**

22- On student registration form add drop down of carrier with phone field.  **(Adil)  (Fixed)**

Values of Carrier for SMS API (DropDown )
1- Telenor: 92345
2- Mobilink: 92300
3- Ufone: 92333
4- Warid: 92321
5- Zong: 92312

**Comment by adilshehbaz** [comment]
Still issues remaining, Feedback By Tariq Sb.
1-On Attendance Show Verify button when they open attendance tab to check Present day attendance 

2-On Student Profile Month not working properly

3-Previous school tab show for all ....but in coment write their (for academy only)

4-sms log generl search problem date wise

5-section subject active inactive not working

6-Test drop down remove from test screen

**Comment by nawabanjum** [comment]
11- Add All Old Present and Other Fields on Test Report Which is Hidden in New Report **(Fixed)**

12- Test Report Print Change T(1) to T-1 **(Fixed)**

**Comment by adilshehbaz** [comment]
send sms once to every one in 24 hours


General SMS...msg 2300

search all data

Attendance Detail Full Month

Test Information not showing proper data

for academy only red color

**Comment by nawabanjum** [comment]
15- If New Student Added His Test Report in This Class **(Fixed)**

**Comment by nawabanjum** [comment]
21- Quick Registeration form on student (only required field show) (nawab)

22- On student registration form add drop down of carrier with phone field. (nawab)

Values of Carrier for SMS API (DropDown ) (nawab)
1- Telenor: 92345
2- Mobilink: 92300
3- Ufone: 92333
4- Warid: 92321
5- Zong: 92312
